// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// corr_slide_cpp
List corr_slide_cpp(NumericMatrix timeseries, int window, int step);
RcppExport SEXP _dynR_corr_slide_cpp(SEXP timeseriesSEXP, SEXP windowSEXP, SEXP stepSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type timeseries(timeseriesSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    Rcpp::traits::input_parameter< int >::type step(stepSEXP);
    rcpp_result_gen = Rcpp::wrap(corr_slide_cpp(timeseries, window, step));
    return rcpp_result_gen;
END_RCPP
}
// dyn_phase_lock_cpp
NumericVector dyn_phase_lock_cpp(NumericMatrix phases);
RcppExport SEXP _dynR_dyn_phase_lock_cpp(SEXP phasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type phases(phasesSEXP);
    rcpp_result_gen = Rcpp::wrap(dyn_phase_lock_cpp(phases));
    return rcpp_result_gen;
END_RCPP
}
// get_leida_cpp
NumericMatrix get_leida_cpp(NumericVector sync_conn);
RcppExport SEXP _dynR_get_leida_cpp(SEXP sync_connSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type sync_conn(sync_connSEXP);
    rcpp_result_gen = Rcpp::wrap(get_leida_cpp(sync_conn));
    return rcpp_result_gen;
END_RCPP
}
// kuramoto_sync_cpp
NumericVector kuramoto_sync_cpp(NumericMatrix phases);
RcppExport SEXP _dynR_kuramoto_sync_cpp(SEXP phasesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type phases(phasesSEXP);
    rcpp_result_gen = Rcpp::wrap(kuramoto_sync_cpp(phases));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_dynR_corr_slide_cpp", (DL_FUNC) &_dynR_corr_slide_cpp, 3},
    {"_dynR_dyn_phase_lock_cpp", (DL_FUNC) &_dynR_dyn_phase_lock_cpp, 1},
    {"_dynR_get_leida_cpp", (DL_FUNC) &_dynR_get_leida_cpp, 1},
    {"_dynR_kuramoto_sync_cpp", (DL_FUNC) &_dynR_kuramoto_sync_cpp, 1},
    {NULL, NULL, 0}
};

RcppExport void R_init_dynR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
