# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Sliding-window Pearson correlation (C++ backend)
#'
#' Internal workhorse called by [corr_slide()]. Computes Pearson correlation
#' matrices directly on the input matrix without allocating per-window
#' submatrices or calling R's `cor()`.
#'
#' Loop ordering is chosen for cache efficiency on the column-major R matrix:
#' the innermost loop over `t` (timepoints) within a window iterates over
#' consecutive memory locations in each column of `timeseries`, so the
#' cross-product accumulation step is sequential in memory.
#'
#' @param timeseries NumericMatrix \[N x Tmax\].
#' @param window Integer window size in timepoints.
#' @param step Integer step between window onsets.
#'
#' @return List with:
#'   \item{corr_mats}{NumericVector with dim \[N, N, n_windows\].}
#'   \item{idx}{IntegerVector of 1-indexed window onset positions.}
#'
#' @keywords internal
corr_slide_cpp <- function(timeseries, window, step) {
    .Call(`_dynR_corr_slide_cpp`, timeseries, window, step)
}

#' Instantaneous phase-locking matrices (C++ backend)
#'
#' Internal workhorse called by [dyn_phase_lock()]. Iterates over the trimmed
#' timepoints (dropping the first and last 10) and fills an \[N, N, n_T\]
#' array with \eqn{\cos(\phi_i - \phi_j)} for every parcel pair.
#'
#' Exploits the symmetry \eqn{\cos(a-b) = \cos(b-a)}: only the upper triangle
#' is computed via \code{std::cos}; the diagonal is set to 1 directly, and
#' values are mirrored to the lower triangle. This halves the number of
#' trigonometric evaluations relative to a naive double loop.
#'
#' @param phases NumericMatrix \[N x Tmax\]. Instantaneous phases in radians,
#'   as returned by [hilbert_phases()].
#'
#' @return A NumericVector with a \code{dim} attribute \[N, N, n_T\] (i.e. a
#'   3-D array), where \code{n_T = Tmax - 20}.
#'
#' @keywords internal
dyn_phase_lock_cpp <- function(phases) {
    .Call(`_dynR_dyn_phase_lock_cpp`, phases)
}

#' Leading eigenvector decomposition (LEiDA) -- C++ / LAPACK backend
#'
#' Internal workhorse called by [get_leida()]. For each phase-locking matrix
#' slice in `sync_conn`, calls LAPACK `dsyev` (symmetric eigendecomposition)
#' and returns only the leading eigenvector.
#'
#' Differences from the R implementation:
#' - `dsyev` returns eigenvalues in **ascending** order, so the leading
#'   eigenvector is the **last** column of the output (opposite of R's
#'   `eigen()` which is descending).
#' - The LAPACK workspace is allocated once and reused across all timepoints.
#' - Sign convention preserved: row sum forced to be non-positive.
#'
#' @param sync_conn NumericVector with `dim` attribute \[N, N, t_points\].
#'
#' @return NumericMatrix \[t_points x N\]. Leading eigenvectors, one per row.
#'
#' @keywords internal
get_leida_cpp <- function(sync_conn) {
    .Call(`_dynR_get_leida_cpp`, sync_conn)
}

#' Kuramoto order parameter time series (C++ backend)
#'
#' Internal workhorse called by [kuramoto()]. For each trimmed timepoint,
#' computes the global Kuramoto order parameter R(t):
#'
#' \deqn{R(t) = \frac{1}{N} \left| \sum_{j=1}^{N} e^{i\phi_j(t)} \right|}
#'
#' The complex exponential is decomposed as \eqn{\cos\phi + i\sin\phi};
#' the modulus is \eqn{\sqrt{(\sum\cos)^2 + (\sum\sin)^2} / N}, avoiding
#' any R complex-number allocation.
#'
#' The first and last 10 timepoints are discarded (matching [dyn_phase_lock()]).
#'
#' @param phases NumericMatrix \[N x Tmax\]. Instantaneous phases in radians.
#'
#' @return NumericVector \[Tmax-20\]. Kuramoto order parameter per timepoint.
#'
#' @keywords internal
kuramoto_sync_cpp <- function(phases) {
    .Call(`_dynR_kuramoto_sync_cpp`, phases)
}

