# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Instantaneous phase-locking matrices (C++ backend)
#'
#' Internal workhorse called by [dyn_phase_lock()]. Iterates over the trimmed
#' timepoints (dropping the first and last 10) and fills an \[N, N, n_T\]
#' array with \eqn{\cos(\phi_i - \phi_j)} for every parcel pair.
#'
#' Exploits the symmetry \eqn{\cos(a-b) = \cos(b-a)}: only the upper triangle
#' is computed via \code{std::cos}; the diagonal is set to 1 directly, and
#' values are mirrored to the lower triangle. This halves the number of
#' trigonometric evaluations relative to a naive double loop.
#'
#' @param phases NumericMatrix \[N x Tmax\]. Instantaneous phases in radians,
#'   as returned by [hilbert_phases()].
#'
#' @return A NumericVector with a \code{dim} attribute \[N, N, n_T\] (i.e. a
#'   3-D array), where \code{n_T = Tmax - 20}.
#'
#' @keywords internal
dyn_phase_lock_cpp <- function(phases) {
    .Call(`_dynR_dyn_phase_lock_cpp`, phases)
}

